a=int(input("enter a first value:"))
b=int(input("enter a second value:"))
A=(a+b)
S=(a-b)
M=(a*b)
D=(a/b)
FD=(a//b)
MD=(a%b)
E=(a**b)
T=(A+S+M+D+FD+MD+E)
print("sum of",a,"and",b,"is:",A)
print("difference between",a,"and",b,"is:",S)
print("multiplication of",a,"and",b,"is:",M)
print("division of",a,"and",b,"is:",D)
print("floor division of",a,"and",b,"is:",FD)
print("modulu division of",a,"and",b,"is:",MD)
print("exponention of",a,"and",b,"is:",E)
print("sum of all arithematic values of",a,"and",b,"is:",T)
