a=int(input("enter a first value:"))
b=int(input("enter a second value:"))
L=(a<b)
G=(a>b)
LE=(a<=b)
GE=(a>=b)
E=(a==b)
NE=(a!=b)
print(a,"less than",b,"is:",L)
print(a,"greater than",b,"is:",G)
print(a,"less than or equal to",b,"is:",LE)
print(a,"greater than or equal to",b,"is:",GE)
print(a,"equal to",b,"is:",E)
print(a,"not equal to",b,"is:",NE)
